export const studentCourses = [
  {
    codigo: "ECOB40",
    componenteCurricular: "INTRODUÇÃO À ECONOMIA I",
    ch: 60,
    turma: "120000",
    dias: "SEX",
    horario: "8:50/12:30",
    local: "ECO/304",
    docente: "Luiz Alberto Bastos Petitinga",
  },
  {
    codigo: "MATH101",
    componenteCurricular: "CÁLCULO I",
    ch: 80,
    turma: "120001",
    dias: "SEG/QUA",
    horario: "13:00/16:30",
    local: "MAT/201",
    docente: "Maria da Silva",
  },
  {
    codigo: "PHY201",
    componenteCurricular: "FÍSICA I",
    ch: 70,
    turma: "120002",
    dias: "TER/QUI",
    horario: "9:00/12:00",
    local: "FIS/101",
    docente: "Carlos Ferreira",
  },
  {
    codigo: "COMP202",
    componenteCurricular: "PROGRAMAÇÃO AVANÇADA",
    ch: 90,
    turma: "120003",
    dias: "QUA",
    horario: "14:00/17:00",
    local: "CIC/301",
    docente: "Ana Oliveira",
  },
  {
    codigo: "ENG101",
    componenteCurricular: "INGLÊS BÁSICO",
    ch: 40,
    turma: "120004",
    dias: "QUI/SAB",
    horario: "10:00/11:30",
    local: "IDI/102",
    docente: "John Smith",
  },
];
