export const courseClasses = [
  {
    codigo: "ECOB40",
    componenteCurricular: "INTRODUÇÃO À ECONOMIA I",
    ch: 60,
    turma: "001",
    dias: "SEX",
    horario: "8:50/12:30",
    local: "ECO/304",
    docente: "Luiz Alberto Bastos Petitinga",
  },
  {
    codigo: "ECOB40",
    componenteCurricular: "INTRODUÇÃO À ECONOMIA I",
    ch: 60,
    turma: "002",
    dias: "SEG",
    horario: "10:00/13:30",
    local: "ECO/305",
    docente: "Ana Clara de Oliveira Santos",
  },
  {
    codigo: "ECOB40",
    componenteCurricular: "INTRODUÇÃO À ECONOMIA I",
    ch: 60,
    turma: "003",
    dias: "TER",
    horario: "14:00/17:30",
    local: "ECO/306",
    docente: "João Pedro da Silva Costa",
  },
  {
    codigo: "ECOB40",
    componenteCurricular: "INTRODUÇÃO À ECONOMIA I",
    ch: 60,
    turma: "004",
    dias: "QUA",
    horario: "9:00/12:30",
    local: "ECO/307",
    docente: "Ana Clara de Oliveira Santos",
  },
  {
    codigo: "ECOB40",
    componenteCurricular: "INTRODUÇÃO À ECONOMIA I",
    ch: 60,
    turma: "005",
    dias: "QUI",
    horario: "13:00/16:30",
    local: "ECO/308",
    docente: "João Pedro da Silva Costa",
  },
];
