export const professores = [
  {
    name: "A definir",
    value: "a-definir",
    id: 0,
  },
  {
    name: "Andrea Valentina Tatiane Assis",
    value: "955.068.670-18",
    id: 1,
  },
  {
    name: "Bianca Marli da Paz",
    value: "907.352.340-00",
    id: 2,
  },
  {
    name: "Cristiane Nicole Helena das Neves",
    value: "976.961.130-11",
    id: 3,
  },
  {
    name: "Davi Alexandre Theo Barbosa",
    value: "022.769.620-46",
    id: 4,
  },
];

export const disciplinas = [
  { id: 1, name: "MATA02 CÁLCULO A", value: "MATA02" },
  { id: 2, name: "MATA37 INTRODUÇÃO À LÓGICA DE PROGRAMAÇÃO", value: "MATA37" },
  { id: 3, name: "MATA39 SEMINÁRIOS DE INTRODUÇÃO AO CURSO", value: "MATA39" },
  { id: 4, name: "MATA42 MATEMÁTICA DISCRETA I", value: "MATA42" },
  { id: 5, name: "MATA68 COMPUTADOR, ÉTICA E SOCIEDADE", value: "MATA68" },
  { id: 6, name: "ADME99 ECONOMIA DA INOVAÇÃO", value: "ADME99" },
  { id: 7, name: "MATC73 INTRODUÇÃO À LÓGICA MATEMÁTICA", value: "MATC73" },
  { id: 8, name: "MATC90 CIRCUITOS DIGITAIS E ARQUITETURA DE COMPUTADORES", value: "MATC90" },
  { id: 9, name: "MATC92 FUNDAMENTOS DE SISTEMAS DE INFORMAÇÃO", value: "MATC92" },
  { id: 10, name: "MATD04 ESTRUTURAS DE DADOS", value: "MATD04" },
  { id: 11, name: "ADM001 INTRODUCÃO À ADMINISTRACAO", value: "ADM001" },
  { id: 12, name: "MATA07 ÁLGEBRA LINEAR A", value: "MATA07" },
  { id: 13, name: "MATA55 PROGRAMAÇÃO ORIENTADA A OBJETOS", value: "MATA55" },
  { id: 14, name: "MATA58 SISTEMAS OPERACIONAIS", value: "MATA58" },
  { id: 15, name: "MATC94 INTRODUÇÃO AS LINGUAGENS FORMAIS E TEORIA DA COMPUTAÇÃO", value: "MATC94" },
  { id: 16, name: "MATD06 BANCO DE DADOS", value: "MATD06" },
  { id: 17, name: "MATD07 ENGENHARIA DE SOFTWARE", value: "MATD07" },
  { id: 18, name: "MATA76 COMPILADORES", value: "MATA76" },
  { id: 19, name: "MATC82 TÓPICOS ESPECIAIS EM INFORMÁTICA", value: "MATC82" },
  { id: 20, name: "MATA60 REDES DE COMPUTADORES", value: "MATA60" },
  { id: 21, name: "MATD02 INTELIGÊNCIA ARTIFICIAL", value: "MATD02" },
  { id: 22, name: "MATA56 PROGRAMAÇÃO PARALELA E CONCORRENTE", value: "MATA56" },
  { id: 23, name: "MATA89 COMPUTAÇÃO GRÁFICA", value: "MATA89" },
  { id: 24, name: "MATD03 SISTEMAS MULTIMÍDIA", value: "MATD03" },
  { id: 25, name: "MATA88 SISTEMAS DISTRIBUÍDOS", value: "MATA88" },
  { id: 26, name: "BIOF93 BIOQUÍMICA", value: "BIOF93" },
  { id: 27, name: "ENGF93 ENGENHARIA DE PRODUÇÃO", value: "ENGF93" },
  { id: 28, name: "FISF94 FÍSICA QUÂNTICA", value: "FISF94" },
  { id: 29, name: "QUIF92 QUÍMICA ORGÂNICA", value: "QUIF92" },
  { id: 30, name: "MATF91 GEOMETRIA ANALÍTICA", value: "MATF91" },
  { id: 31, name: "ECOF90 ECONOMIA BRASILEIRA", value: "ECOF90" },
  { id: 32, name: "DIRF91 DIREITO CONSTITUCIONAL", value: "DIRF91" },
  { id: 33, name: "PSIF92 PSICOLOGIA SOCIAL", value: "PSIF92" },
  { id: 34, name: "SOCF93 SOCIOLOGIA DA EDUCAÇÃO", value: "SOCF93" },
  { id: 35, name: "EDCF94 EDUCAÇÃO FÍSICA ESCOLAR", value: "EDCF94" },
  { id: 36, name: "HISF93 HISTÓRIA DO BRASIL", value: "HISF93" },
  { id: 37, name: "ARQF94 ARQUITETURA E URBANISMO", value: "ARQF94" },
  { id: 38, name: "MUSF92 MÚSICA E SOCIEDADE", value: "MUSF92" },
  { id: 39, name: "LETF91 LITERATURA BRASILEIRA", value: "LETF91" },
  { id: 40, name: "PEDF90 PEDAGOGIA DA EDUCAÇÃO", value: "PEDF90" },
  { id: 41, name: "ENFF91 ENFERMAGEM E SAÚDE PÚBLICA", value: "ENFF91" },
  { id: 42, name: "MEDF92 MEDICINA INTERNA", value: "MEDF92" },
  { id: 43, name: "ODOF93 ODONTOLOGIA RESTAURADORA", value: "ODOF93" },
  { id: 44, name: "FARF94 FARMACOLOGIA CLÍNICA", value: "FARF94" },
  { id: 45, name: "VETF95 VETERINÁRIA E ZOOTECNIA", value: "VETF95" },
];

export const dias = [
  { id: 1, name: "SEG", value: "SEG" },
  { id: 2, name: "TER", value: "TER" },
  { id: 3, name: "QUA", value: "QUA" },
  { id: 4, name: "QUI", value: "QUI" },
  { id: 5, name: "SEX", value: "SEX" },
  { id: 6, name: "SAB", value: "SAB" },
  { id: 7, name: "DOM", value: "DOM" },
  { id: 8, name: "A Combinar", value: "combinar" },
];

export const horarios = [
  { id: 1, name: "07:00", value: "07:00" },
  { id: 2, name: "07:55", value: "07:55" },
  { id: 3, name: "08:50", value: "08:50" },
  { id: 4, name: "09:45", value: "09:45" },
  { id: 5, name: "10:40", value: "10:40" },
  { id: 6, name: "11:35", value: "11:35" },
  // intervalo sem aula
  { id: 7, name: "13:00", value: "13:00" },
  { id: 8, name: "13:55", value: "13:55" },
  { id: 9, name: "14:50", value: "14:50" },
  { id: 10, name: "15:45", value: "15:45" },
  { id: 11, name: "16:40", value: "16:40" },
  { id: 12, name: "17:35", value: "17:35" },
  { id: 13, name: "18:30", value: "18:30" },
  { id: 14, name: "19:25", value: "19:25" },
  { id: 15, name: "20:20", value: "20:20" },
  { id: 16, name: "21:15", value: "21:15" },
  { id: 17, name: "22:10", value: "22:10" },
];
