export const courseSubjects = {
  nome: "Ciência da Computação",
  grade: [
    {
      periodo: 1,
      disciplinas: [
        {
          id: "cc101",
          nome: "Introdução à Computação",
          codigo: "IC001",
          chPratica: 20,
          chTeorica: 40,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Fundamentos da computação",
            objetivos: "Introduzir os fundamentos da computação",
            conteudo:
              "Algoritmos, estruturas de dados básicas, lógica de programação",
            bibliografia: "Livro A, Livro B, Livro C",
          },
        },
        {
          id: "cc102",
          nome: "Matemática Discreta",
          codigo: "MD001",
          chPratica: 10,
          chTeorica: 50,
          departamento: "Matemática",
          ementa: {
            ementa: "Conceitos matemáticos para ciência da computação",
            objetivos: "Apresentar conceitos matemáticos relevantes",
            conteudo:
              "Lógica, teoria dos conjuntos, relações, álgebra booleana",
            bibliografia: "Livro X, Livro Y",
          },
        },
        {
          id: "cc201",
          nome: "Estruturas de Dados 1",
          codigo: "ED001",
          chPratica: 30,
          chTeorica: 40,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Estruturas de dados e suas aplicações",
            objetivos: "Estudar estruturas de dados e algoritmos associados",
            conteudo: "Listas, pilhas, filas, árvores, grafos",
            bibliografia: "Livro D, Livro E",
          },
        },
        {
          id: "cc202",
          nome: "Programação Orientada a Objetos",
          codigo: "POO001",
          chPratica: 40,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios da programação orientada a objetos",
            objetivos: "Aprender a programar usando POO",
            conteudo: "Classes, objetos, herança, polimorfismo",
            bibliografia: "Livro F, Livro G",
          },
        },
        {
          id: "mat101",
          nome: "Cálculo I",
          codigo: "CALC001",
          chPratica: 40,
          chTeorica: 30,
          departamento: "Matemática",
          ementa: {
            ementa: "Princípios da programação orientada a objetos",
            objetivos: "Aprender a programar usando POO",
            conteudo: "Classes, objetos, herança, polimorfismo",
            bibliografia: "Livro F, Livro G",
          },
        },
      ],
    },
    {
      periodo: 2,
      disciplinas: [
        {
          id: "cc201",
          nome: "Estruturas de Dados 2",
          codigo: "ED002",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Estruturas de dados e suas aplicações",
            objetivos: "Estudar estruturas de dados e algoritmos associados",
            conteudo: "Listas, pilhas, filas, árvores, grafos",
            bibliografia: "Livro J, Livro K",
          },
        },
        {
          id: "cc202",
          nome: "Banco de Dados",
          codigo: "BD001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Fundamentos de banco de dados",
            objetivos:
              "Introduzir conceitos de gerenciamento de banco de dados",
            conteudo: "Modelagem de dados, SQL, normalização",
            bibliografia: "Livro L, Livro M",
          },
        },
        {
          id: "cc203",
          nome: "Algoritmos Avançados",
          codigo: "AA001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Algoritmos avançados e análise de complexidade",
            objetivos: "Estudar algoritmos avançados e sua eficiência",
            conteudo:
              "Divisão e conquista, programação dinâmica, algoritmos gulosos",
            bibliografia: "Livro N, Livro O",
          },
        },
        {
          id: "cc204",
          nome: "Arquitetura de Computadores",
          codigo: "AC001",
          ch: 60,
          chPratica: 20,
          chTeorica: 40,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Arquitetura e organização de computadores",
            objetivos: "Compreender o funcionamento de computadores",
            conteudo: "Processadores, memória, dispositivos de entrada/saída",
            bibliografia: "Livro P, Livro Q",
          },
        },
        {
          id: "cc205",
          nome: "Inglês Técnico",
          codigo: "IT001",
          ch: 30,
          chPratica: 10,
          chTeorica: 20,
          departamento: "Idiomas",
          ementa: {
            ementa: "Inglês técnico para computação",
            objetivos: "Desenvolver habilidades de comunicação em inglês",
            conteudo:
              "Vocabulário técnico, leitura e compreensão de textos técnicos",
            bibliografia: "Livro R, Livro S",
          },
        },
      ],
    },
    {
      periodo: 3,
      disciplinas: [
        {
          id: "cc301",
          nome: "Sistemas Operacionais",
          codigo: "SO001",
          ch: 60,
          chPratica: 20,
          chTeorica: 40,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios de sistemas operacionais",
            objetivos: "Compreender o funcionamento de sistemas operacionais",
            conteudo: "Processos, memória, sistemas de arquivos, concorrência",
            bibliografia: "Livro T, Livro U",
          },
        },
        {
          id: "cc302",
          nome: "Redes de Computadores",
          codigo: "RC001",
          ch: 60,
          chPratica: 20,
          chTeorica: 40,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Fundamentos de redes de computadores",
            objetivos: "Estudar a comunicação em redes",
            conteudo: "Modelos de redes, protocolos, segurança",
            bibliografia: "Livro V, Livro W",
          },
        },
        {
          id: "cc303",
          nome: "Estruturas de Dados Avançadas",
          codigo: "EDA001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Estruturas de dados avançadas e algoritmos",
            objetivos: "Estudar estruturas de dados complexas",
            conteudo:
              "Árvores balanceadas, grafos, algoritmos de busca e ordenação",
            bibliografia: "Livro X, Livro Y",
          },
        },
        {
          id: "cc304",
          nome: "Engenharia de Software",
          codigo: "ES001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios de engenharia de software",
            objetivos: "Desenvolver habilidades em engenharia de software",
            conteudo: "Ciclo de vida de software, documentação, teste",
            bibliografia: "Livro Z, Livro AA",
          },
        },
        {
          id: "cc305",
          nome: "Banco de Dados Avançado",
          codigo: "BDA001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Tópicos avançados em banco de dados",
            objetivos:
              "Estudar tópicos avançados em gerenciamento de banco de dados",
            conteudo: "Modelagem avançada, indexação, transações",
            bibliografia: "Livro BB, Livro CC",
          },
        },
      ],
    },
    {
      periodo: 4,
      disciplinas: [
        {
          id: "cc401",
          nome: "Inteligência Artificial",
          codigo: "IA001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Fundamentos de inteligência artificial",
            objetivos: "Estudar técnicas de inteligência artificial",
            conteudo:
              "Agentes inteligentes, aprendizado de máquina, redes neurais",
            bibliografia: "Livro DD, Livro EE",
          },
        },
        {
          id: "cc402",
          nome: "Sistemas Distribuídos",
          codigo: "SD001",
          ch: 60,
          chPratica: 20,
          chTeorica: 40,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios de sistemas distribuídos",
            objetivos: "Compreender a computação em ambientes distribuídos",
            conteudo: "Comunicação em rede, coordenação, segurança",
            bibliografia: "Livro FF, Livro GG",
          },
        },
        {
          id: "cc403",
          nome: "Compiladores",
          codigo: "COMP001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios de construção de compiladores",
            objetivos: "Estudar a construção de compiladores",
            conteudo: "Análise léxica, análise sintática, geração de código",
            bibliografia: "Livro HH, Livro II",
          },
        },
        {
          id: "cc404",
          nome: "Segurança da Informação",
          codigo: "SI001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios de segurança da informação",
            objetivos: "Estudar técnicas de segurança da informação",
            conteudo: "Criptografia, autenticação, políticas de segurança",
            bibliografia: "Livro JJ, Livro KK",
          },
        },
        {
          id: "cc405",
          nome: "Ética e Responsabilidade Social",
          codigo: "ERS001",
          ch: 30,
          chPratica: 10,
          chTeorica: 20,
          departamento: "Filosofia",
          ementa: {
            ementa: "Ética e responsabilidade social na tecnologia",
            objetivos: "Refletir sobre questões éticas na computação",
            conteudo: "Privacidade, ética profissional, impacto social",
            bibliografia: "Livro LL, Livro MM",
          },
        },
      ],
    },
    {
      periodo: 5,
      disciplinas: [
        {
          id: "cc501",
          nome: "Desenvolvimento Web Avançado",
          codigo: "DWA001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Desenvolvimento avançado de aplicações web",
            objetivos: "Estudar tecnologias avançadas para web",
            conteudo: "Frameworks, APIs, segurança web",
            bibliografia: "Livro NN, Livro OO",
          },
        },
        {
          id: "cc502",
          nome: "Computação Gráfica",
          codigo: "CG001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Princípios de computação gráfica",
            objetivos: "Estudar técnicas de processamento gráfico",
            conteudo: "Renderização, modelagem 3D, animação",
            bibliografia: "Livro PP, Livro QQ",
          },
        },
        {
          id: "cc503",
          nome: "Projeto de Software",
          codigo: "PS001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Métodos e técnicas de projeto de software",
            objetivos: "Desenvolver habilidades em projeto de software",
            conteudo: "UML, padrões de projeto, documentação",
            bibliografia: "Livro RR, Livro SS",
          },
        },
        {
          id: "cc504",
          nome: "Big Data e Análise de Dados",
          codigo: "BDAD001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Tecnologias para lidar com grandes volumes de dados",
            objetivos: "Estudar técnicas de análise de dados em larga escala",
            conteudo: "Hadoop, Spark, análise estatística",
            bibliografia: "Livro TT, Livro UU",
          },
        },
        {
          id: "cc505",
          nome: "Empreendedorismo em Tecnologia",
          codigo: "ET001",
          ch: 30,
          chPratica: 10,
          chTeorica: 20,
          departamento: "Administração",
          ementa: {
            ementa: "Empreendedorismo e inovação em tecnologia",
            objetivos: "Desenvolver habilidades empreendedoras",
            conteudo: "Plano de negócios, startups, financiamento",
            bibliografia: "Livro VV, Livro WW",
          },
        },
      ],
    },
    {
      periodo: 6,
      disciplinas: [
        {
          id: "cc601",
          nome: "Aprendizado de Máquina",
          codigo: "AM001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Fundamentos de aprendizado de máquina",
            objetivos: "Estudar algoritmos de aprendizado de máquina",
            conteudo:
              "Aprendizado supervisionado, não supervisionado, redes neurais",
            bibliografia: "Livro XX, Livro YY",
          },
        },
        {
          id: "cc602",
          nome: "Projeto de Redes de Computadores",
          codigo: "PRC001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Projeto avançado de redes de computadores",
            objetivos: "Desenvolver habilidades em projeto de redes",
            conteudo: "Projeto de redes locais e de longa distância, segurança",
            bibliografia: "Livro ZZ, Livro AAA",
          },
        },
        {
          id: "cc603",
          nome: "Sistemas de Informação",
          codigo: "SI002",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Sistemas de informação corporativos",
            objetivos: "Estudar sistemas de informação em organizações",
            conteudo: "ERP, CRM, gestão de projetos",
            bibliografia: "Livro BBB, Livro CCC",
          },
        },
        {
          id: "cc604",
          nome: "Ética na Tecnologia",
          codigo: "ET002",
          ch: 30,
          chPratica: 10,
          chTeorica: 20,
          departamento: "Filosofia",
          ementa: {
            ementa: "Ética na tecnologia e questões sociais",
            objetivos: "Refletir sobre questões éticas na era digital",
            conteudo: "Privacidade online, ética de IA, inclusão digital",
            bibliografia: "Livro DDD, Livro EEE",
          },
        },
        {
          id: "cc605",
          nome: "Tópicos Avançados em Ciência da Computação",
          codigo: "TACC001",
          ch: 60,
          chPratica: 30,
          chTeorica: 30,
          departamento: "Ciência da Computação",
          ementa: {
            ementa: "Tópicos avançados em ciência da computação",
            objetivos: "Explorar tópicos avançados de pesquisa",
            conteudo: "Varia de acordo com o tópico do semestre",
            bibliografia: "Depende do tópico do semestre",
          },
        },
      ],
    },
  ],
};
