export const courses = [
  {
    codigo: "316130",
    nome: "Administração",
    periodoCurriculo: 2016,
    turno: "Diurno",
    duracaoMinima: 4,
    duracaoMaxima: 7,
  },
  {
    codigo: "316131",
    nome: "Ciências Contábeis",
    periodoCurriculo: 2016,
    turno: "Diurno",
    duracaoMinima: 4,
    duracaoMaxima: 7,
  },
  {
    codigo: "316132",
    nome: "Ciências Econômicas",
    periodoCurriculo: 2016,
    turno: "Diurno",
    duracaoMinima: 4,
    duracaoMaxima: 7,
  },
  {
    codigo: "316133",
    nome: "Direito",
    periodoCurriculo: 2016,
    turno: "Diurno",
    duracaoMinima: 5,
    duracaoMaxima: 10,
  },
  {
    codigo: "316134",
    nome: "Psicologia",
    periodoCurriculo: 2016,
    turno: "Diurno",
    duracaoMinima: 5,
    duracaoMaxima: 10,
  },
  {
    codigo: "316135",
    nome: "Administração",
    periodoCurriculo: 2016,
    turno: "Noturno",
    duracaoMinima: 4,
    duracaoMaxima: 7,
  },
  {
    codigo: "316136",
    nome: "Ciências Contábeis",
    periodoCurriculo: 2016,
    turno: "Noturno",
    duracaoMinima: 4,
    duracaoMaxima: 7,
  },
  {
    codigo: "316137",
    nome: "Ciências Econômicas",
    periodoCurriculo: 2016,
    turno: "Noturno",
    duracaoMinima: 4,
    duracaoMaxima: 7,
  },
  {
    codigo: "316138",
    nome: "Direito",
    periodoCurriculo: 2016,
    turno: "Noturno",
    duracaoMinima: 5,
    duracaoMaxima: 10,
  },
  {
    codigo: "316139",
    nome: "Psicologia",
    periodoCurriculo: 2016,
    turno: "Noturno",
    duracaoMinima: 5,
    duracaoMaxima: 10,
  },
];
